// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: proto/harpocrate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HarpocrateClient is the client API for Harpocrate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HarpocrateClient interface {
	// Reduce link length by according a random ID to a link
	Reduce(ctx context.Context, in *ReduceRequest, opts ...grpc.CallOption) (*ReduceReponse, error)
}

type harpocrateClient struct {
	cc grpc.ClientConnInterface
}

func NewHarpocrateClient(cc grpc.ClientConnInterface) HarpocrateClient {
	return &harpocrateClient{cc}
}

func (c *harpocrateClient) Reduce(ctx context.Context, in *ReduceRequest, opts ...grpc.CallOption) (*ReduceReponse, error) {
	out := new(ReduceReponse)
	err := c.cc.Invoke(ctx, "/gravitalia.harpocrate.v1.Harpocrate/Reduce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HarpocrateServer is the server API for Harpocrate service.
// All implementations must embed UnimplementedHarpocrateServer
// for forward compatibility
type HarpocrateServer interface {
	// Reduce link length by according a random ID to a link
	Reduce(context.Context, *ReduceRequest) (*ReduceReponse, error)
	mustEmbedUnimplementedHarpocrateServer()
}

// UnimplementedHarpocrateServer must be embedded to have forward compatible implementations.
type UnimplementedHarpocrateServer struct {
}

func (UnimplementedHarpocrateServer) Reduce(context.Context, *ReduceRequest) (*ReduceReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reduce not implemented")
}
func (UnimplementedHarpocrateServer) mustEmbedUnimplementedHarpocrateServer() {}

// UnsafeHarpocrateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HarpocrateServer will
// result in compilation errors.
type UnsafeHarpocrateServer interface {
	mustEmbedUnimplementedHarpocrateServer()
}

func RegisterHarpocrateServer(s grpc.ServiceRegistrar, srv HarpocrateServer) {
	s.RegisterService(&Harpocrate_ServiceDesc, srv)
}

func _Harpocrate_Reduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarpocrateServer).Reduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravitalia.harpocrate.v1.Harpocrate/Reduce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarpocrateServer).Reduce(ctx, req.(*ReduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Harpocrate_ServiceDesc is the grpc.ServiceDesc for Harpocrate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Harpocrate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gravitalia.harpocrate.v1.Harpocrate",
	HandlerType: (*HarpocrateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reduce",
			Handler:    _Harpocrate_Reduce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/harpocrate.proto",
}
