// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: proto/harpocrate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumerate every possible options
type Option int32

const (
	// Disable analytics and url analysis
	Option_DISABLE_BOTH Option = 0
	// Do not count each click (may result in faster redirection).
	Option_DISABLE_ANALYTICS Option = 1
	// Do not check whether the link is a phising website (may result in faster savings).
	Option_DISABLE_ANALYSIS Option = 2
)

// Enum value maps for Option.
var (
	Option_name = map[int32]string{
		0: "DISABLE_BOTH",
		1: "DISABLE_ANALYTICS",
		2: "DISABLE_ANALYSIS",
	}
	Option_value = map[string]int32{
		"DISABLE_BOTH":      0,
		"DISABLE_ANALYTICS": 1,
		"DISABLE_ANALYSIS":  2,
	}
)

func (x Option) Enum() *Option {
	p := new(Option)
	*p = x
	return p
}

func (x Option) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Option) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_harpocrate_proto_enumTypes[0].Descriptor()
}

func (Option) Type() protoreflect.EnumType {
	return &file_proto_harpocrate_proto_enumTypes[0]
}

func (x Option) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Option.Descriptor instead.
func (Option) EnumDescriptor() ([]byte, []int) {
	return file_proto_harpocrate_proto_rawDescGZIP(), []int{0}
}

// Request message containing url and option
type ReduceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// URL to reduce
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Author who entered the URL
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// Optional state to disable custom analysis
	Opt *Option `protobuf:"varint,3,opt,name=opt,proto3,enum=gravitalia.harpocrate.v1.Option,oneof" json:"opt,omitempty"`
}

func (x *ReduceRequest) Reset() {
	*x = ReduceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_harpocrate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceRequest) ProtoMessage() {}

func (x *ReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_harpocrate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceRequest.ProtoReflect.Descriptor instead.
func (*ReduceRequest) Descriptor() ([]byte, []int) {
	return file_proto_harpocrate_proto_rawDescGZIP(), []int{0}
}

func (x *ReduceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReduceRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ReduceRequest) GetOpt() Option {
	if x != nil && x.Opt != nil {
		return *x.Opt
	}
	return Option_DISABLE_BOTH
}

// Response message containing ID to get a custom short link
type ReduceReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReduceReponse) Reset() {
	*x = ReduceReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_harpocrate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceReponse) ProtoMessage() {}

func (x *ReduceReponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_harpocrate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceReponse.ProtoReflect.Descriptor instead.
func (*ReduceReponse) Descriptor() ([]byte, []int) {
	return file_proto_harpocrate_proto_rawDescGZIP(), []int{1}
}

func (x *ReduceReponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_harpocrate_proto protoreflect.FileDescriptor

var file_proto_harpocrate_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x72, 0x70, 0x6f, 0x63, 0x72, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74,
	0x61, 0x6c, 0x69, 0x61, 0x2e, 0x68, 0x61, 0x72, 0x70, 0x6f, 0x63, 0x72, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x22, 0x7a, 0x0a, 0x0d, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x37, 0x0a,
	0x03, 0x6f, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61,
	0x76, 0x69, 0x74, 0x61, 0x6c, 0x69, 0x61, 0x2e, 0x68, 0x61, 0x72, 0x70, 0x6f, 0x63, 0x72, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03,
	0x6f, 0x70, 0x74, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6f, 0x70, 0x74, 0x22, 0x1f,
	0x0a, 0x0d, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x2a,
	0x47, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x53,
	0x41, 0x42, 0x4c, 0x45, 0x5f, 0x42, 0x4f, 0x54, 0x48, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x44,
	0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x41, 0x4e, 0x41, 0x4c, 0x59, 0x54, 0x49, 0x43, 0x53,
	0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x41, 0x4e,
	0x41, 0x4c, 0x59, 0x53, 0x49, 0x53, 0x10, 0x02, 0x32, 0x68, 0x0a, 0x0a, 0x48, 0x61, 0x72, 0x70,
	0x6f, 0x63, 0x72, 0x61, 0x74, 0x65, 0x12, 0x5a, 0x0a, 0x06, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x12, 0x27, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x69, 0x61, 0x2e, 0x68, 0x61,
	0x72, 0x70, 0x6f, 0x63, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x72, 0x61, 0x76,
	0x69, 0x74, 0x61, 0x6c, 0x69, 0x61, 0x2e, 0x68, 0x61, 0x72, 0x70, 0x6f, 0x63, 0x72, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x74, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74,
	0x61, 0x6c, 0x69, 0x61, 0x2e, 0x68, 0x61, 0x72, 0x70, 0x6f, 0x63, 0x72, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x42, 0x0f, 0x48, 0x61, 0x72, 0x70, 0x6f, 0x63, 0x72, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x69, 0x61, 0x2f, 0x68, 0x61, 0x72,
	0x70, 0x6f, 0x63, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x18,
	0x47, 0x72, 0x61, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x69, 0x61, 0x2e, 0x48, 0x61, 0x72, 0x70, 0x6f,
	0x63, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_harpocrate_proto_rawDescOnce sync.Once
	file_proto_harpocrate_proto_rawDescData = file_proto_harpocrate_proto_rawDesc
)

func file_proto_harpocrate_proto_rawDescGZIP() []byte {
	file_proto_harpocrate_proto_rawDescOnce.Do(func() {
		file_proto_harpocrate_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_harpocrate_proto_rawDescData)
	})
	return file_proto_harpocrate_proto_rawDescData
}

var file_proto_harpocrate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_harpocrate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_harpocrate_proto_goTypes = []interface{}{
	(Option)(0),           // 0: gravitalia.harpocrate.v1.Option
	(*ReduceRequest)(nil), // 1: gravitalia.harpocrate.v1.ReduceRequest
	(*ReduceReponse)(nil), // 2: gravitalia.harpocrate.v1.ReduceReponse
}
var file_proto_harpocrate_proto_depIdxs = []int32{
	0, // 0: gravitalia.harpocrate.v1.ReduceRequest.opt:type_name -> gravitalia.harpocrate.v1.Option
	1, // 1: gravitalia.harpocrate.v1.Harpocrate.Reduce:input_type -> gravitalia.harpocrate.v1.ReduceRequest
	2, // 2: gravitalia.harpocrate.v1.Harpocrate.Reduce:output_type -> gravitalia.harpocrate.v1.ReduceReponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_harpocrate_proto_init() }
func file_proto_harpocrate_proto_init() {
	if File_proto_harpocrate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_harpocrate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_harpocrate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_harpocrate_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_harpocrate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_harpocrate_proto_goTypes,
		DependencyIndexes: file_proto_harpocrate_proto_depIdxs,
		EnumInfos:         file_proto_harpocrate_proto_enumTypes,
		MessageInfos:      file_proto_harpocrate_proto_msgTypes,
	}.Build()
	File_proto_harpocrate_proto = out.File
	file_proto_harpocrate_proto_rawDesc = nil
	file_proto_harpocrate_proto_goTypes = nil
	file_proto_harpocrate_proto_depIdxs = nil
}
